[tool.black]
line-length = 120
target-version = ['py38']
include = '\.pyi?$'

exclude = '''
(
  /(
      \.eggs
    | \.git
    | \.gitignore
    | \.hg
    | \.mypy_cache
    | \.tox
    | \.venv
    | \.python-version
    | \.env
  )
)
'''
